site_name: scmRTOS
#site_url: ''
#use_directory_urls: false

theme:
    name: readthedocs
    custom_dir: overrides
    max_width: 2000
    navigation_depth: 5
    font: false
    features:
        - content.code.copy
        - content.code.annotate
    #name: windmill


extra_css: 
    - extra.css


nav:
    - Synopsys                           : index.md 
    - Features                           : features.md
    - Supported Platforms                : platforms.md

    - Intro:
        - Preface                        : src/preface.md 
        - Overview                       : src/overview.md
    
    - RTOS Components:
        - Kernel                         : src/kernel.md
        - Processes                      : src/processes.md
        - Interprocess Communications    : src/ipcs.md
        - Ports                          : src/ports.md

    - Appendix:
        - Debug                          : src/debug.md
        - Process Profiling              : src/profiler.md
        - 'Example: Job Queue'           : src/example-job-queue.md
        - Glossary                       : src/glossary.md

extra_javascript:
    - js/mathjax.js
    - js/mathjax/tex-mml-chtml.js
    #- js/wavedrom.min.js
    #- js/wavedrom_loader.js
    #- js/wavedrom.unpkg.js
    #- js/wavedrom_skin_default.js


markdown_extensions:
    - toc:
        permalink: "üîó"
        baselevel: 1
    - pymdownx.arithmatex:
       generic: true    
    - admonition
    - attr_list
    - footnotes
    - markdown_wavedrom
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tilde
    - pymdownx.betterem
    - pymdownx.blocks.caption
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.snippets

plugins:
    - search:
        lang: en

    - i18n:
          docs_structure: folder
          languages:
            - locale: en
              name: English
              build: true
              default: true
            - locale: ru
              name: –†—É—Å—Å–∫–∏–π
              build: true
              nav:
                - –û–±—â–∏–µ —Å–≤–µ–¥–µ–Ω–∏—è                     : index.md 
                - –•–∞—Ä–∞–∫—Ç–µ—Ä–∏—Å—Ç–∏–∫–∏                     : features.md
                - –ü–æ–¥–¥–µ—Ä–∂–∏–≤–∞–µ–º—ã–µ –ø–ª–∞—Ç—Ñ–æ—Ä–º—ã           : platforms.md

                - –í–≤–µ–¥–µ–Ω–∏–µ:
                    - –ü—Ä–µ–¥–∏—Å–ª–æ–≤–∏–µ                    : src/preface.md 
                    - –û–±–∑–æ—Ä –æ–ø–µ—Ä–∞—Ü–∏–æ–Ω–Ω–æ–π —Å–∏—Å—Ç–µ–º—ã     : src/overview.md
                
                - –ö–æ–º–ø–æ–Ω–µ–Ω—Ç—ã:
                    - –Ø–¥—Ä–æ                           : src/kernel.md
                    - –ü—Ä–æ—Ü–µ—Å—Å—ã                       : src/processes.md
                    - –ú–µ–∂–ø—Ä–æ—Ü–µ—Å—Å–Ω–æ–µ –≤–∑–∞–∏–º–æ–¥–µ–π—Å—Ç–≤–∏–µ   : src/ipcs.md
                    - –ü–æ—Ä—Ç—ã                          : src/ports.md

                - –ü—Ä–∏–ª–æ–∂–µ–Ω–∏—è:
                    - –û—Ç–ª–∞–¥–∫–∞                        : src/debug.md
                    - –ü—Ä–æ—Ñ–∏–ª–∏—Ä–æ–≤–∫–∞ –ø—Ä–æ—Ü–µ—Å—Å–æ–≤         : src/profiler.md
                    - '–ü—Ä–∏–º–µ—Ä: –æ—á–µ—Ä–µ–¥—å –∑–∞–¥–∞–Ω–∏–π'      : src/example-job-queue.md
                    - –¢–µ—Ä–º–∏–Ω—ã –∏ —Å–æ–∫—Ä–∞—â–µ–Ω–∏—è           : src/glossary.md


          #default_language: en
          #languages:
          #  en: English
          # ru: –†—É—Å—Å–∫–∏–π

    - glightbox
    #- markdownwavedrom
